[package]
name = "ch02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ch02_0"
path = "src/0/main.rs"

[[bin]]
name = "ch02_1"
path = "src/1/main.rs"



[dependencies]
